futurice_checklist/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import os.path
from employee.views import indexview, employeeview, employeelist, update_employeeinfo, update_employeelist, new_employee, toggle_state_employee
from editlist.views import edit_lists, edit_list, edit_list_item
from reminders.views import reminderhome, remindercreate, reminderedit, reminderview, reminderdelete

urlpatterns = patterns('',
    url(r'^$', indexview, name="index"),
    url(r'^listview/(?P<list_id>[0-9]+)$', employeelist, name='employeelist', kwargs={"template_name": "employeelist.html"}),
    url(r'^listview/(?P<list_id>[0-9]+)/without/(?P<without_item_id>[0-9]+)$', employeelist, name='employeelist-without-item', kwargs={"template_name": "employeelist.html"}),
    url(r'^employeeview/(?P<employee_id>[0-9]+)$', employeeview, name='employeeview', kwargs={"template_name": "employeeview.html"}),
    url(r'^new_employee$', new_employee, name='new_employee', kwargs={"template_name": "new_employee.html"}),
    url(r'^update/employee/state/(?P<action>[a-z]+)/(?P<employee_id>[0-9]+)$', toggle_state_employee, name="x_employee"),
    url(r'^update/employeeinfo/(?P<employee_id>[0-9]+)$', update_employeeinfo, kwargs={"template_name": 'data_posted.html'}, name="update_info"),
    url(r'^update/employeelist/(?P<employee_id>[0-9]+)/(?P<item_id>[0-9]+)$', update_employeelist, kwargs={"template_name": 'data_posted.html'}, name="update_employee"),

    url(r'^edit/(?P<list_id>[0-9]+)/add$', edit_list_item, kwargs={"template_name": "edit_list_item.html", "action": "new", "item_id": 0}, name="edit_check"),
    url(r'^edit/(?P<list_id>[0-9]+)/edit/(?P<item_id>[0-9]+)$', edit_list_item, kwargs={"template_name": "edit_list_item.html", "action": "edit"}, name="edit_list_item"),
    url(r'^edit/(?P<list_id>[0-9]+)$', edit_list, kwargs={"template_name": "edit_list.html"}, name="edit_list"),
    url(r'^edit$', edit_lists, kwargs={"template_name": "edit_lists.html"}, name="edit"),

    url(r'^reminders$', reminderhome, kwargs={"template_name": "home.html"}, name="reminders"),
    url(r'^reminders/create$', remindercreate, kwargs={"template_name": "edit.html"}, name="reminder_create"),
    url(r'^reminders/edit/(?P<list_id>[0-9]+)$', reminderedit, kwargs={"template_name": "edit.html"}, name="reminder_edit"),
    url(r'^reminders/delete/(?P<list_id>[0-9]+)$', reminderdelete, kwargs={"template_name": "delete.html"}, name="reminder_delete"),
    url(r'^reminders/(?P<list_id>[0-9]+)$', reminderview, kwargs={"template_name": "view.html"}, name="reminder_view"),

    url(r'^checklist/static/(?P<path>.*)$', 'django.views.static.serve',  {'document_root': os.path.join(os.path.dirname(__file__), 'static')}),

    # https://docs.djangoproject.com/en/dev/ref/contrib/admin/#reversing-admin-urls
    url(r'^admin/', include(admin.site.urls)),
)

employee/models.py
from django.db import models
import datetime
import markdown

USER_GROUPS = (
   ("IT", "IT"),
   ("HR", "HR admin"),
   ("SU", "Supervisor"),
   ("DH", "HR"),
   ("DA", "ADMIN"),
   ("DS", "DE Supervisor"),
   ("UN", "Undefined")
)

class UserPermissions(models.Model):
    username = models.CharField(max_length=50)
    group = models.CharField(max_length=2, choices=USER_GROUPS, default='UN')

    def __unicode__(self):
        return "%s: %s" % (self.username, self.group)

    class Meta:
        ordering = ('username', )
        verbose_name_plural = 'User permissions'


class EmployeeItemLog(models.Model):
    employee = models.ForeignKey('Employee')
    timestamp = models.DateTimeField(auto_now_add=True)
    item = models.ForeignKey('ChecklistItem')
    value = models.BooleanField(default=False)
    textvalue = models.CharField(max_length=200,blank=True, null=True)

class EmployeeLog(models.Model):
    employee = models.ForeignKey('Employee')
    timestamp = models.DateTimeField(auto_now_add=True)
    changes = models.TextField()

class Checklist(models.Model):
    listname = models.CharField(max_length=200)
    def __unicode__(self):
        return self.listname

class Checkpoint(models.Model):
    deadline = models.IntegerField(verbose_name="Days before starting date")
    send_alarm = models.BooleanField(default=True)

    def __unicode__(self):
        return str(self.deadline)

    class Meta:
        ordering = ('deadline',)

class ChecklistItem(models.Model):
    class Meta:
        ordering = ('listname', 'unit','order','itemname')

    listname = models.ForeignKey('Checklist')
    itemname = models.CharField(max_length=200, verbose_name="Item Name", help_text="Name shown in checklist")
    textbox = models.BooleanField(default=False, verbose_name="Enable Textbox", help_text="Optional textbox next to checklist item for additional data")
    order = models.IntegerField(verbose_name="Order in Checklist")
    unit = models.CharField(max_length=50, verbose_name="Responsible Team", help_text="Only single team: IT/HR admin/Finance/Supervisor")
    item_pair = models.ForeignKey('ChecklistItem', null=True, blank=True)
    checkpoint = models.ForeignKey('Checkpoint', null=True, blank=True, help_text="Optional. Not yet implemented, just skip.")

    def markdown_itemname(self):
        result = markdown.markdown(self.itemname)
        p_start, p_end = '<p>', '</p>'
        if result.startswith(p_start) and result.endswith(p_end):
            result = result[len(p_start):-len(p_end)]
        return result

    def __unicode__(self):
        return self.itemname

EMPLOYEE_STATES= (
    ('S', 'Summer worker'),
    ('P', 'Part-timer'),
    ('T', 'Fixed-term'),
    ('A', 'Permanent'),
    ('E', 'External'),
)

LOCATIONS = (
    ('U', 'Unknown'),
    ('B', 'Berlin'),
    ('H', 'Helsinki'),
    ('L', 'Lontoo'),
    ('M', 'Munich'),
    ('S', 'Stockholm'),
    ('T', 'Tampere'),
)

class Employee(models.Model):
    listname = models.ForeignKey('Checklist')
    name = models.CharField(max_length=100)
    ldap_account = models.CharField(max_length=10, blank=True)
    start_date = models.DateField(verbose_name="Date")
    confirmed = models.BooleanField(default=False, verbose_name="Confirmed")
    archived = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    
    employee_state = models.CharField(max_length=1, choices=EMPLOYEE_STATES, default='A')
    location = models.CharField(max_length=1, choices=LOCATIONS, default='U')
    phone = models.CharField(max_length=30, blank=True, verbose_name="Phone number")
    email = models.CharField(max_length=150, blank=True, verbose_name="Contact email")
    email_notifications = models.BooleanField(default=True)
    supervisor = models.CharField(max_length=50, blank=True, verbose_name="Supervisor")
    tribe = models.CharField(max_length=50, blank=True, verbose_name="Tribe")
    comments = models.TextField(max_length=1500, blank=True, verbose_name="Info")

    @property
    def eta(self):
        return (self.start_date - datetime.date.today()).days


    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('start_date', 'name')

class EmployeeItem(models.Model):
    listname = models.ForeignKey('Checklist')
    employee = models.ForeignKey('Employee')
    item = models.ForeignKey('ChecklistItem')
    value = models.BooleanField(default=False)
    textvalue = models.CharField(max_length=200,blank=True, null=True)
    comment = models.CharField(max_length=200, blank=True)
    checkpoint_fired = models.BooleanField(default=False)

    class Meta:
        unique_together = (
                ('listname', 'employee', 'item'),
        )

    def __unicode__(self):
        return "%s: %s - %s" % (self.employee.name, self.item.itemname, self.value)

employee/views.py
from django.template import RequestContext, loader
from django.contrib.auth import get_backends
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.conf import settings
from django.shortcuts import redirect, render, render_to_response, get_object_or_404

from employee.forms import NewEmployee, EmployeeHeader, ListItemForm, DeleteForm
from employee.models import Checklist, ChecklistItem, Employee, EmployeeItem, UserPermissions
from employee.util import determine_group

from datetime import date
import itertools
import json


def fill_employee_extra(employee, viewer_username, viewer_unit):
    """
    Add extra fields to the Employee object.

    employee - Employee object
    viewer_username - the username of the viewer (performing the web request)
    viewer_unit - string returned by determine_group(...)
    """
    employee.total_count = ChecklistItem.objects.filter(listname=employee.listname).count()
    employee.done_count = EmployeeItem.objects.filter(employee=employee, listname=employee.listname, value=True).count()
    employee.your_total_count = ChecklistItem.objects.filter(listname=employee.listname, unit=viewer_unit).count()
    employee.your_done_count = EmployeeItem.objects.filter(employee=employee, listname=employee.listname, item__unit=viewer_unit, value=True).count()
    if employee.supervisor == viewer_username:
        employee.your_employee = True

def indexview(request):
    ret = {}
    unit = determine_group(request.user.username)
    if unit != "Undefined":
        ret["authorized"] = True
    lists = Checklist.objects.all()
    my_items = Employee.objects.filter(ldap_account=request.user.username).order_by("start_date")
    ret["my_items"] = my_items
    ret["lists"] = lists

    all_employees = Employee.objects.filter(deleted=False)
    employees_unarchived = all_employees.filter(archived=False)
    employees_archived = all_employees.filter(archived=True)
    for employee in itertools.chain(employees_unarchived, employees_archived):
        fill_employee_extra(employee, request.user.username, unit)
    ret['employees'] = employees_unarchived
    ret['archived'] = employees_archived

    return render(request, 'index.html', ret)

def toggle_state_employee(request, action, employee_id):
    unit = determine_group(request.user.username)
    if unit == "Undefined":
        return render_to_response("common/unauthorized.html", {}, context_instance=RequestContext(request))
    employee = get_object_or_404(Employee, pk=employee_id)
    if action == "delete":
        employee.deleted = not employee.deleted
    if action == "archive":
        employee.archived = not employee.archived
    employee.save()
    url = reverse('employeeview', kwargs={'employee_id': employee.id})
    return HttpResponseRedirect(url)

def employeelist(request, template_name, list_id, without_item_id=None):
    unit = determine_group(request.user.username)
    if unit == "Undefined":
        return render_to_response("common/unauthorized.html", {}, context_instance=RequestContext(request))
    chklist = Checklist.objects.get(id=list_id)
    all_employees = Employee.objects.filter(listname=list_id, deleted=False)

    # exclude employees who have this item ticked
    without_item = None
    if without_item_id is not None:
        without_item = ChecklistItem.objects.get(id=without_item_id)
        empl_id_with_item = all_employees.filter(
                employeeitem__item_id=without_item_id,
                employeeitem__value=True).values('id')
        all_employees = all_employees.exclude(id__in=empl_id_with_item)

    employees_unarchived = all_employees.filter(archived=False)
    employees_archived = all_employees.filter(archived=True)

    for employee in itertools.chain(employees_unarchived, employees_archived):
        fill_employee_extra(employee, request.user.username, unit)
        try:
            employee.textvalue = EmployeeItem.objects.get(
                    employee_id=employee.id, item=without_item,
                    listname=employee.listname).textvalue
        except EmployeeItem.DoesNotExist:
            pass

    return render_to_response(template_name, {
        'chklist': chklist,
        'employees': employees_unarchived,
        'archived': employees_archived,
        'without_item': without_item,
        'without_item_url': reverse('employeelist',
            kwargs={'list_id': chklist.id}),
    }, context_instance=RequestContext(request))


def __combine_lists(employee_dict, items):
    listitems = []
    for item in items:
        d = {}
        if employee_dict.has_key(item.id):
            d["value"] = employee_dict[item.id].value
            d["textvalue"] = employee_dict[item.id].textvalue
        d["itemname"] = item.itemname
        d["markdown_itemname"] = item.markdown_itemname()
        d["textbox"] = item.textbox
        d["id"] = item.id
        d["unit"] = item.unit
        listitems.append(d)
    return listitems

def employeeview(request, template_name, employee_id):
    employee = Employee.objects.get(id=employee_id)
    unit = determine_group(request.user.username)
    if employee.ldap_account != request.user.username:
        if unit == "Undefined":
            return render_to_response("common/unauthorized.html", {}, context_instance=RequestContext(request))
    items_yours = ChecklistItem.objects.filter(listname=employee.listname.id).filter(unit=unit)
    items_others = ChecklistItem.objects.filter(listname=employee.listname.id).exclude(unit=unit)

    employee_items = EmployeeItem.objects.filter(employee=employee)
    employee_dict = {}
    for item in employee_items:
        employee_dict[item.item.id] = item

    form = EmployeeHeader(instance=employee)

    listitems_yours = __combine_lists(employee_dict, items_yours)
    listitems_others = __combine_lists(employee_dict, items_others)
    return render_to_response(template_name, {'listitems_yours': listitems_yours, 'listitems_others': listitems_others, 'employee': employee, 'employee_form': form }, context_instance=RequestContext(request))

def update_employeelist(request, template_name, employee_id, item_id):
    employee = Employee.objects.get(id=employee_id)
    listitem = ChecklistItem.objects.get(id=item_id)
    (employee_item, created) = EmployeeItem.objects.get_or_create(employee=employee, item=listitem, listname=employee.listname)
    unit = determine_group(request.user.username)
    if employee.ldap_account != request.user.username:
        if unit == "Undefined":
            return render_to_response("common/unauthorized.html", {}, context_instance=RequestContext(request))

    if "checkbox" in request.POST.keys():
        if request.POST["checkbox"] == 'on' or request.POST["checkbox"] == 'true' or request.POST["checkbox"] == "checked":
            employee_item.value = True
        else:
            employee_item.value = False
    else:
        employee_item.value = False
    keys = employee_item.value

    if "textbox" in request.POST.keys():
        employee_item.textvalue = request.POST["textbox"]

    employee_item.save()
    keys = {"success": True, "key": listitem.id, "employee_item_id": employee_item.id, "value": employee_item.value}
    keys = json.dumps(keys)
    return render_to_response(template_name, {"keys": keys }, context_instance=RequestContext(request))

def update_employeeinfo(request, template_name, employee_id):
    employee = Employee.objects.get(id=employee_id)
    keys = {"success": True, "form": "headerform", "key": "header"}
    unit = determine_group(request.user.username)
    if employee.ldap_account != request.user.username:
        if unit == "Undefined":
            return render_to_response("common/unauthorized.html", {}, context_instance=RequestContext(request))
    if request.method == 'POST':
        formset = EmployeeHeader(request.POST, instance=employee)
        if formset.is_valid():
            formset.save()
        else:
            keys["success"] = False

    keys = json.dumps(keys)
    return render_to_response(template_name, {"keys": keys}, context_instance=RequestContext(request))

def new_employee(request, template_name):
    unit = determine_group(request.user.username)
    if unit == "Undefined":
        return render_to_response("common/unauthorized.html", {}, context_instance=RequestContext(request))
    if request.method == 'POST': # If the form has been submitted...
        form = NewEmployee(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            employee = form.save(commit=False)
            employee.save()
            url = reverse('employeeview', kwargs={'employee_id': employee.id})
            return HttpResponseRedirect(url) # Redirect after POST
    else:
        form = NewEmployee() # An unbound form

    return render_to_response(template_name, {'form': form}, context_instance=RequestContext(request))

employee/templates/data_posted.html
{{ keys|safe }}

employee/templates/employee_listitems.html
{% comment %}
    Employee list items table used by employeeview.html.
    Arguments: employee (Employee), listitems (list of custom objects),
        csrf_token.
{% endcomment %}

{% load staticfiles %}

{% for listitem in listitems %}
<form method="post" action="{% url "update_employee" employee.id listitem.id %}" class="autosave form_listitem" id="form_{{ listitem.id }}" name="form_{{ listitem.id }}" autocomplete="off">
{% csrf_token %}
<div class="dwrap">
    <div class="dwrap_saving"><img src="{% static "common/blank.png" %}" id="progress_{{ listitem.id }}"></div>
<div class="dwrap_1"><input type="checkbox" name="checkbox" {% if listitem.value %}checked="checked"{%endif%} id="checkbox"></div>
<div class="dwrap_2"><small>{{ listitem.unit }}</small></div>
<div class="dwrap_3">
  <a class="all_without"
     href="{% url 'employeelist-without-item' list_id=employee.listname.id without_item_id=listitem.id %}"
     title="See everyone without {{listitem.itemname}}"
  >⚙</a>
  {{ listitem.markdown_itemname|safe }}
</div>
<div class="dwrap_4">{% if listitem.textbox %}<input  type="textbox" value="{{ listitem.textvalue }}" name="textbox" id="textbox">{% endif %}</div>
</div>
</form>
{% endfor %}

<div style="clear:both;margin-top:2em;"></div>

employee/templates/employeelist.html
{% extends "common/base.html" %}
{% load staticfiles %}

{% block header %}
<link rel="stylesheet" href="{{CDN_URL}}js/select2-3.5.2/select2.css">
<script src="{{CDN_URL}}js/select2-3.5.2/select2.js"></script>
{% endblock %}

{% block content %}

<h1 class="page-header">{{ chklist.listname }}</h1>

<h3>
  Without:
  <select id="without-item-selector">
    <!-- empty <option> required by select2 to allow unselecting -->
    <option></option>
    {% for chkitem in chklist.checklistitem_set.filter %}
      <option
          value="{{chkitem.id}}"
          href="{% url "employeelist-without-item" list_id=chklist.id without_item_id=chkitem.id %}"
          {% if chkitem.id == without_item.id %}selected{% endif %}
          >
        {{chkitem.itemname}}
      </option>
    {% endfor %}
  </select>
</h3>

<script type="text/javascript">
$("#without-item-selector").select2({
  placeholder: 'Select a checklist item',
  allowClear: true
}).on('change', function(e) {
  var href;
  if (!e.val) {
    href = '{% url "employeelist" list_id=chklist.id %}';
  } else {
    var sel = e.target;
    var option = sel[sel.selectedIndex];
    href = option.getAttribute('href');
  }
  window.location.href = href;
});
</script>

<h2>Active employees</h2>
{% include "employeetable.html" with employees=employees archived=False without_item=without_item without_item_url=without_item_url csrf_token=csrf_token only %}

<h2>Archived employees</h2>
{% include "employeetable.html" with employees=archived archived=True without_item=without_item without_item_url=without_item_url csrf_token=csrf_token only %}

<script type="text/javascript">
var BLANK = "{% static "common/transparent.png" %}";
var OK = "{% static "common/ok.png" %}";
var SPINNER = "{% static "common/spinner14.gif" %}";

var timeouts = Array();

function switch_blank(node) {
    $(node).attr("src", BLANK);
}

$(document).ready(function() {
  function get_autosave_options(empl_id) {
    return {
      grouped: false,
      send: function(data) {
        var idname = "#progress_"+empl_id;
        $(idname).attr("src", SPINNER);
      },
      success: function(data) {
        if (data.success == true) {
          var idname = "#progress_"+empl_id;
          $(idname).attr("src", OK);
          if (typeof timeouts[idname] != 'undefined') {
            clearTimeout(timeouts[idname]);
          }
          timeouts[idname] = setTimeout("switch_blank('"+idname+"');", 1500);
        } else {
          console.log("fail");
        }
      }
    };
  }

  {% for empl in employees %}
    $("#form_{{empl.id}}").autosave(get_autosave_options({{empl.id}}));
  {% endfor %}
  {% for empl in archived %}
    $("#form_{{empl.id}}").autosave(get_autosave_options({{empl.id}}));
  {% endfor %}
});
</script>

{% endblock %}

employee/templates/employeetable.html
{% comment %}
    Employee table used by employeelist.html.
    Arguments: employees (list of custom objects), archived (bool),
        show_list_name (bool),
        without_item (ChecklistItem), without_item_url, csrf_token.
{% endcomment %}

{% load staticfiles %}

<table class="table {% if archived %}table-striped{% endif %} table-condensed">
<thead>
 <tr>
  <th>S</th>
  <th>L</th>
  <th>Name</th>
  {% if without_item %}
    <th>
      {{without_item.markdown_itemname|safe}}
      <a href="{{without_item_url}}" title="remove filter">
        <i class="icon-remove"></i>
      </a>
    </th>
  {% endif %}
  {% if show_list_name %}
    <th>List</th>
  {% endif %}
  <th>
    {% if archived %}
      Start date
    {% else %}
      Date
    {% endif %}
  </th>
  <th>Confirmed</th>
  <th>ETA</th>
  <th>Group items</th>
  <th>Items done</th>
 </tr>
</thead>
<tbody>
{% for employee in employees %}
 <tr class="{% if employee.your_employee %}your_employee{%endif%} {% if not archived %}{% if employee.eta < 0 %}old{% else %}new{% endif %}{% endif %}">
  <td>{% ifnotequal employee.employee_state 'A' %}{{ employee.employee_state }}{% endifnotequal %}</td>
  <td>{{ employee.location }}</td>
  <td><a href="{% url "employeeview" employee.id %}">{{ employee.name }}</a></td>
  {% if without_item %}
    <td>
      <form method="post" action="{% url "update_employee" employee.id without_item.id %}" class="autosave" id="form_{{employee.id}}" autocomplete="off">
        {% csrf_token %}
        <img src="{% static 'common/transparent.png' %}" id="progress_{{employee.id}}">
        <input type="checkbox" name="checkbox">
        {% if without_item.textbox %}
            <input type="textbox" value="{{employee.textvalue}}"
              name="textbox" class="without_item_textbox">
        {% endif %}
      </form>
    </td>
  {% endif %}

  {% if show_list_name %}
    <td>
      <a href="{% url "employeelist" list_id=employee.listname.id %}"
         >{{employee.listname.listname}}</a>
    </td>
  {% endif %}

  <td>{{ employee.start_date|date:"Y-m-d" }}</td>
  <td><i class="{% if employee.confirmed %}icon-ok{% else %}icon-remove{% endif %}"></i></td>
  <td>{{ employee.eta }} day{{ employee.eta|pluralize}}</td>
  <td>{% if employee.your_done_count == employee.your_total_count %}<b>Finished</b>{%else%}<b>{{ employee.your_done_count }}</b>/{{ employee.your_total_count }}{%endif%}</td>
  <td>{% if employee.done_count == employee.total_count %}<b>Finished</b>{%else%}<b>{{ employee.done_count }}</b>/{{ employee.total_count }}{%endif%}</td>
 </tr>
{% endfor %}
</tbody>
</table>

employee/templates/employeeview.html
{% extends "common/base.html" %}
{% load staticfiles %}

{% block content %}

<script type="text/javascript">
var BLANK = "{% static "common/blank.png" %}";
var OK = "{% static "common/ok.png" %}";
var SPINNER = "{% static "common/spinner14.gif" %}";
$.log = function(message){
     $('#log').append('<p>' + message + '</p>');
};

var timeouts = Array();

function switch_blank(node) {
    $(node).attr("src", BLANK);
}
function process_success(data) {
   if (data.success == true) {
    idname = "#progress_"+data.key;
    $(idname).attr("src", OK);
    if (typeof timeouts[idname] != 'undefined') {
      clearTimeout(timeouts[idname]);
    }
    timeouts[idname] = setTimeout("switch_blank('"+idname+"');", 1500);
   } else {
    console.log("fail");
   }
}

function process_send(data) {
    id = $(data).closest('form').attr("id").split("_");
    id = id[1];
    idname = "#progress_"+id;
    $(idname).attr("src", SPINNER);
}

$(document).ready(function(){
 $("#id_start_date").datepicker({'dateFormat': 'yy-mm-dd', 'showWeek': true, 'firstDay': 1});
 $("#form_header").autosave({
  grouped: true,
  success: function(data) { process_success(data) },
  send: function(data) { process_send(data) }
 });
 var autosave_options = {grouped: false, success: function(data) { process_success(data) }, send: function(data) { process_send(data) }  };

 {% for listitem in listitems_yours %}
  $("#form_{{ listitem.id }}").autosave(autosave_options); {% endfor %}
 {% for listitem in listitems_others %}
  $("#form_{{ listitem.id }}").autosave(autosave_options); {% endfor %}

});

</script>

<h1>{{ employee.name }}</h1>

{% if employee.archived %}
<a href="{% url "x_employee" "archive" employee.id %}" id="archive_user" class="btn">Unarchive</a>
{% else %}
<a href="{% url "x_employee" "archive" employee.id %}" id="archive_user" class="btn btn-warning">Archive</a>
{% endif %}

{% if employee.deleted %}
<a href="{% url "x_employee" "delete" employee.id %}" id="delete_user" class="btn">Undelete</a>
{% else %}
<a href="{% url "x_employee" "delete" employee.id %}" id="delete_user" class="btn btn-danger">Delete</a>
{% endif %}

<form method="post" action="{% url "update_info" employee.id %}" class="autosave" id="form_header" autocomplete="off">
{% csrf_token %}
<legend><img src="{% static "common/blank.png" %}" id="progress_header"></legend>
<table id="employee-form-table">
{{ employee_form }}
</table>
</form>

<h1>Your items</h1>
<p>Please note: additional items in list below this (<b>Other items</b>) may also apply to you. You should not ignore it.</p>
{% include "employee_listitems.html" with employee=employee listitems=listitems_yours csrf_token=csrf_token only %}

<h1>Other items</h1>
{% include "employee_listitems.html" with employee=employee listitems=listitems_others csrf_token=csrf_token only %}

{% endblock %}

employee/templates/index.html
{% extends "common/base.html" %}

{% block content %}
<div class="row">
<div class="span12">
{% if not my_items and not authorized %}
		<h1>Checklist software</h1>
		<p>You don't have any checklists, and you don't have permission to view other's lists.</p>
{% endif %}
{% if my_items %}
<h1>Your items</h1>

<ul>
{% for empl in my_items %}
<li><a href="{% url 'employeeview' employee_id=empl.id %}">{{ empl.listname }} - {{ empl.start_date }}</a></li>
{% endfor %}
</ul>

{% endif %}

{% if authorized %}
<h2>Active employees</h2>
{% include "employeetable.html" with employees=employees archived=False show_list_name=True csrf_token=csrf_token only %}

<h2>Archived employees</h2>
{% include "employeetable.html" with employees=archived archived=True show_list_name=True csrf_token=csrf_token only %}
{% endif %}

</div>
</div>
{% endblock %}

employee/templates/new_employee.html
{% extends "common/base.html" %}

{% block content %}
<script type="text/javascript">
 $(function() {
  $("#id_start_date").datepicker({"dateFormat": "yy-mm-dd", 'showWeek': true, 'firstDay': 1});
 });
</script>

<h1>Add new employee to checklist</h1>

<table>
<form action="{% url "new_employee" %}" method="post">
{% csrf_token %}
{{ form }}
<tr>
<th></th>
<td><input type="submit" value="Submit" name="submit"></td>
</tr>
</form>
</table>
{% endblock %}